- .eslintrc.js
- README.md
- package-lock.json
- package.json
Anthony and I configured Eslint and Prettier along with Husky to
auto-format on commit.
- [NA] I have added tests that prove my fix is effective or that my feature works
- [NA] New and existing unit tests pass locally with my changes
> Set up linting and formatting

- README.md
- READMEoriginal.md
> Readme update

- database/migrations/20191105000804_createTables.js
- database/migrations/Users_postgres_create.sql
- database/seeds/01_users.js
- database/seeds/02-properties.js
- database/seeds/03-tenanthistory.js
- database/seeds/04-workorders.js
- database/seeds/05-wohistory.js
- src/index.html
- src/server.js
Just an idea to have a visual guide. This does not really "fix" any issue or have a feature. It's more internal information.
> Base root index.html

- database/migrations/20191105000804_createTables.js
- database/seeds/02-properties.js
- database/seeds/03-tenanthistory.js
- database/seeds/04-workorders.js
- database/seeds/05-wohistory.js
> update names to camelCase

- src/index.html
> Index Page Documentation

- src/index.html
> Update to Endpoints

- database/migrations/20191105000804_createTables.js
- database/seeds/01_users.js
- src/routes/properties/property-model.js
- src/routes/properties/property-model.test.js
minor updates that didn't get pushed earlier
- Bug fix (non-breaking change which fixes an issue)
- Complete, tested, ready to review and merge
- Jest
> Property schema model

- src/index.html
- src/routes/properties/property-model.js
- src/routes/properties/property-model.test.js
- src/routes/properties/property-router.js
- src/routes/properties/property-router.test.js
Updating Property endpoints.
- New feature (non-breaking change which adds functionality)
- This change requires a documentation update
- Complete, tested, ready to review and merge
- Jest and SuperTest
- My code follows the style guidelines of this project
- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
- I have made corresponding changes to the documentation
- My changes generate no new warnings
- I have added tests that prove my fix is effective or that my feature works
- New and existing unit tests pass locally with my changes
- There are no merge conflicts
> Property endpoint - get

- src/controllers/auth/index.js
- src/server.js
While working with the front end team to get redux hooked up and get the
auth flow worked out we encountered a handful of errors that required
some additional work on the backend. This PR encompasses the changes
that needed to be made
- [N/A] I have made corresponding changes to the documentation
> Fix firebase auth issues

- src/routes/properties/property-model.js
- src/routes/properties/property-model.test.js
- src/routes/properties/property-router.js
- src/routes/properties/property-router.test.js
Add Property endpoints
- New feature (non-breaking change which adds functionality)
- This change requires a documentation update
- Complete, tested, ready to review and merge
- Jest and SuperTest
- My code follows the style guidelines of this project
- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
- My changes generate no new warnings
- I have added tests that prove my fix is effective or that my feature works
- New and existing unit tests pass locally with my changes
- There are no merge conflicts
> Property create

- src/index.html
- src/routes/properties/property-model.js
- src/routes/properties/property-model.test.js
- src/routes/properties/property-router.js
- src/routes/properties/property-router.test.js
- New feature (non-breaking change which adds functionality)
- This change requires a documentation update
- Jest and SuperTest
> Property Model and Routes

- database/seeds/01_users.js
- database/seeds/02-properties.js
- database/seeds/03-tenanthistory.js
Update Seed Data to add more options for testing.
- npx knex migrate:rollback : Batch 1 rolled back: 1 migrations
- npx knex migrate:latest : Batch 1 run: 1 migrations
- npx knex seed:run : Ran 6 seed files
> Update Seed Data

- database/migrations/20191216192322_update_user_for_tenants.js
- src/models/user/user.js
- src/routes/tenants/index.js
- src/routes/tenants/tenants.js
- src/routes/tenants/tenants.test.js
- src/server.js
This PR allows authorized landlords to create tenants. This PR does not address tenant account creation, just database entry and associations. 
> Add POST /api/tenants endpoint

- database/migrations/20191207121716_create_users.js
- src/controllers/users/index.js
- src/controllers/users/users.js
- src/routes/users/index.js
- src/routes/users/users.js
- src/routes/users/users.test.js
- src/server.js
This PR implements an endpoint for /api/users/me which will send back
basic user info for the endpoint
Fixes #31
> Get basic user info

- src/controllers/users/users.js
- src/lib/bearer-auth.test.js
- src/models/user/user.js
- src/routes/users/users.js
- src/routes/users/users.test.js
This PR adds the ability to edit the user's info at PUT /api/users/me
Fixes #32
> Edit user info endpoint

- src/routes/tenants/tenants.js
- src/routes/tenants/tenants.test.js
- src/test-utils/models.js
> Update Property status to occupied when add tenant

- src/routes/users/users.js
- src/routes/users/users.test.js
The edit user route was letting the user delete their email by passing
null or an empty string. That was silly.
Fixes #40
> Prevent user from deleting their email

- src/models/user/user.js
- src/routes/tenants/tenants.js
- src/routes/tenants/tenants.test.js
> Landlord can get all of their tenants

- src/controllers/auth/index.test.js
- src/middleware/index.js
- src/middleware/require-landlord.js
- src/models/user/user.js
- src/routes/properties/property-router.js
- src/routes/tenants/tenants.js
- src/routes/tenants/tenants.test.js
GET /api/tenants/:id
Fixes #46
> Landlord can get a tenant by id

- src/docs/docs.js
- src/docs/lib/content.js
- src/docs/lib/head.js
- src/server.js
This is only updating documents
> Reformating docs

- src/docs/docs.js
- src/docs/lib/content.js
- src/docs/lib/head.js
- src/server.js
> Work Orders - In Progress

- package-lock.json
- package.json
- src/controllers/auth/index.js
- src/controllers/auth/index.test.js
- src/lib/bearer-auth.js
- src/lib/bearer-auth.test.js
- src/lib/jwt.js
- src/middleware/__tests__/if-landlord-create-user.test.js
- src/middleware/if-landlord-create-user.js
- src/middleware/if-tenant-check-if-authorized.js
- src/middleware/index.js
- src/routes/auth/auth.js
- src/routes/auth/auth.test.js
- src/routes/properties/property-router.test.js
- src/routes/tenants/tenants.test.js
- src/routes/users/users.test.js
This pull request adds jsonwebtoken to the auth flow, and removes the
token provided by Firebase. The firebase token had a short expiration
time, and no mechanism for altering.
> Add JWT handling

- src/controllers/properties/properties.js
- src/controllers/properties/properties.test.js
- src/routes/properties/property-router.js
- src/routes/properties/property-router.test.js
Tenants can now get all properties (which returns the list of properties
they are associated with), as well as request a specific property by id
if they have access.
Fixes # 66 
> Add tenant access to the properties resource

- src/controllers/auth/index.js
- src/controllers/properties/properties.js
- src/models/workorders/workorders.js
- src/models/workorders/workorders.test.js
- src/routes/workorders/wo-router.js
- src/routes/workorders/wo-router.test.js
> Nest property and user in workorder

- .codeclimate.yml
- .github/workflows/ci.yml
- README.md
- package-lock.json
- package.json
Setting up Code Climate
Adding Badges to Repository
> Setting up Code Climate

- .codeclimate.yml
- .github/workflows/ci.yml
- README.md
- package-lock.json
- package.json
- src/docs/data.js
- src/docs/docs.js
- src/docs/lib/functions.js
- src/docs/lib/menu.js
> Updating Code Climate Information

- src/server.js
Removed the origin true indicator on cors. Invoked cors in the middleware and moved it below to be the last one invoked.
Fix for the Cors issue on production
Fix
- [ X ] Bug fix (non-breaking change which fixes an issue)
- [ X ] Complete, but not tested (may need new tests)
- [ X ] My code follows the style guidelines of this project
- [ X ] I have performed a self-review of my own code
- [ X ] My code has been reviewed by at least one peer
- [X  ] My changes generate no new warnings
- [X ] There are no merge conflicts
> Removed origin true from cors.

- src/lib/firebase.js
Added some sanitization to remove /n from the API Key.
Fix for Heroku
Fix
> Parsing the private key to sanitize for next lines.

- .codeclimate.yml
Adding Temp Folder and Test Files to Ignore Patterns for Code Climate
Maintainability Grade
Admin Change
> Modified CodeClimate Ignore Pattern

- database/migrations/20200405085257_unit.js
- database/migrations/20200405085506_message.js
- database/seeds/00_cleanup.js
- src/controllers/unit/unit-controller.js
- src/controllers/workorders/workorders.js
- src/models/unit/unit.js
- src/models/user/user.js
- src/models/workorders/workorders.js
- src/routes/properties/property-router.js
- src/routes/workorders/wo-router.js
- src/server.js
Refactored unit table router, controller, and model
Old code not compatible with new database schema
Refactor
- [x ] New feature (non-breaking change which adds functionality)
- [x ] Incomplete/work-in-progress, PR is for discussion/feedback
> refactored create, read, and update functionality for unit table

- src/controllers/media/media-controller.test.js
100% testing for media controller
refactor
- [x ] My code follows the style guidelines of this project
- [x ] My changes generate no new warnings
- [x ] New and existing unit tests pass locally with my changes
- [x ] There are no merge conflicts
> completed media controller tests

- jest.config.js
Removed inherited config file
Code Climate test coverage
Configuration
- [ x] Bug fix (non-breaking change which fixes an issue)
- [x ] My code follows the style guidelines of this project
- [x ] My code has been reviewed by at least one peer
- [x ] My changes generate no new warnings
- [x ] New and existing unit tests pass locally with my changes
- [x ] There are no merge conflicts
> deleted jest.config.js

- src/controllers/media/media-controller.test.js
- src/controllers/message/message-controller.test.js
- src/controllers/payments/payments-controller.test.js
- src/controllers/unit/unit-controller.test.js
- src/controllers/user/user-controller.test.js
- src/controllers/workorders/workorders-controller.test.js
- src/routes/media/media-router.int.test.js
- src/test-utils/mock-data.js
Moved mock data for tests to it's own file
refactor
- [x ] New feature (non-breaking change which adds functionality)
- [x ] My code follows the style guidelines of this project
- [x ] My changes generate no new warnings
- [x ] New and existing unit tests pass locally with my changes
- [x ] There are no merge conflicts
> moved mock data from individual files to mock data file

- src/controllers/media/media-controller.js
- src/middleware/if-user-exists.js
- src/routes/auth/auth.js
- src/routes/media/media-router.int.test.js
- src/routes/users/index.js
- src/test-utils/mock-data.js
Created first test for the media router
Needed more test coverage
- [x ] New feature (non-breaking change which adds functionality)
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] My code has been reviewed by at least one peer
- [ x] My changes generate no new warnings
- [ x] New and existing unit tests pass locally with my changes
- [ x] There are no merge conflicts
> started testing media router

- src/models/workorders/workorders-model.js
Fixed Work Order Bug that was causing null return
- [ ✔️ ] Bug fix (non-breaking change which fixes an issue)
- [✔️  ] Complete, but not tested (may need new tests)
- [✔️  ] My code follows the style guidelines of this project
- [ ✔️ ] I have performed a self-review of my own code
- [✔️  ] My code has been reviewed by at least one peer
- [✔️  ] I have commented my code, particularly in hard-to-understand areas
- [ ✔️ ] I have made corresponding changes to the documentation
- [✔️  ] My changes generate no new warnings
- [✔️  ] I have added tests that prove my fix is effective or that my feature works
- [✔️  ] New and existing unit tests pass locally with my changes
- [✔️  ] There are no merge conflicts
> Fixed Work Order Return Bug

- src/controllers/workorders/workorders-controller.js
- src/models/unit/unit-model.js
- src/models/user/user-model.js
- src/routes/unit/unit-router.js
Needed middleware to reject post request when adding a property if it already exists
No validation on route
refactor
- [x ] New feature (non-breaking change which adds functionality)
- [x ] My code follows the style guidelines of this project
- [x ] My changes generate no new warnings
- [ x] New and existing unit tests pass locally with my changes
- [x ] There are no merge conflicts
> added middleware to check if property exists when adding a property
